services:
  syncthing-relay:
    image: migel0/syncthing-discosrv:latest
    restart: unless-stopped
    ports:
      - "8443:8443/tcp"
      - "19200:19200/tcp"
    networks:
      - local
    labels:
      - "traefik.enable=false"
    volumes:
      - "syncthing-discosrv:/stdiscosrv"
    command: -cert /stdiscosrv/cert.pem -db-dir /stdiscosrv -key /stdiscosrv/key.pem

volumes:
  syncthing-discosrv:

networks:
  local:
